server:
  port: 9088

spring:
  datasource:
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
    url: jdbc:mysql://127.0.0.1:3306/java_framework
    driver-class-name: com.mysql.jdbc.Driver
    username: yxb
    password: 123456
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
