server:
  port: 9088

spring:
  datasource:
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
    url: jdbc:mysql://127.0.0.1:3306/java_framework
    driver-class-name: com.mysql.jdbc.Driver
    username: yxb
    password: 123456
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5

  redis:
    host: 192.168.31.180
    port: 5673
    timeout: 1000
    password:
    block-when-exhausted: true
    max-idle: 1000
    min-idle: 0
    max-active: 8
    max-wait: 10000
    database: 9


