#Redisson配置
singleServerConfig:
  address: "redis://127.0.0.1:6379"
  password: null
  clientName: client1
  database: 9 #选择使用哪个数据库0~15
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  subscriptionsPerConnection: 5
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  dnsMonitoringInterval: 5000
  #dnsMonitoring: false

threads: 0
nettyThreads: 0
codec:
  class: "org.redisson.codec.JsonJacksonCodec"
transportMode: "NIO"

## 哨兵模式
#sentinelServersConfig:
#  idleConnectionTimeout: 10000
#  pingTimeout: 1000
#  connectTimeout: 10000
#  timeout: 3000
#  retryAttempts: 3
#  retryInterval: 1500
#  reconnectionTimeout: 3000
#  failedAttempts: 3
#  password: 12345678
#  subscriptionsPerConnection: 5
#  clientName: null
#  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
#  slaveSubscriptionConnectionMinimumIdleSize: 1
#  slaveSubscriptionConnectionPoolSize: 50
#  slaveConnectionMinimumIdleSize: 10
#  slaveConnectionPoolSize: 64
#  masterConnectionMinimumIdleSize: 10
#  masterConnectionPoolSize: 64
#  readMode: "SLAVE"
#  sentinelAddresses:
#    - "redis://172.16.33.216:16001"
#    - "redis://172.16.33.216:16002"
#  masterName: "master1"
#  database: 0
#threads: 0
#nettyThreads: 0
#codec: !<org.redisson.codec.JsonJacksonCodec> {}
#useLinuxNativeEpoll: false
#
##主从模式
#clusterServersConfig:
#  idleConnectionTimeout: 10000
#  pingTimeout: 1000
#  connectTimeout: 10000
#  timeout: 3000
#  retryAttempts: 3
#  retryInterval: 1500
#  reconnectionTimeout: 3000
#  failedAttempts: 3
#  password: null
#  subscriptionsPerConnection: 5
#  clientName: null
#  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
#  slaveSubscriptionConnectionMinimumIdleSize: 1
#  slaveSubscriptionConnectionPoolSize: 50
#  slaveConnectionMinimumIdleSize: 32
#  slaveConnectionPoolSize: 64
#  masterConnectionMinimumIdleSize: 32
#  masterConnectionPoolSize: 64
#  readMode: "SLAVE"
#  nodeAddresses:
#    - "redis://127.0.0.1:7004"
#    - "redis://127.0.0.1:7001"
#    - "redis://127.0.0.1:7000"
#  scanInterval: 1000
#threads: 0
#nettyThreads: 0
#codec: !<org.redisson.codec.JsonJacksonCodec> {}
#"transportMode":"NIO"